{adresaAplikacije2: 'http://200.20.0.4:8080/fsabolic_aplikacija_2/api/', adresaAplikacije1: 172.17.0.1,
  OpenSkyNetwork.email: fsabolic@student.foi.hr, OpenWeatherMap.apikey: 119fff17445e4c859971197ee5225a12,
  OpenSkyNetwork.korisnik: FranSabolic, mreznaVrataAplikacije1: '8123'}
